### ISSUE TITLE
incluir link entre git e pagina

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/identidade-digital#12]
Conforme [post no DiscussOKBr](https://discuss.okfn.org/t/manifesto-sobre-identificacao-digital-no-brasil/4203/2), se não houverem objeções, 

* *new issue*: a página [github.io/identidade-digital](https://okfn-brasil.github.io/identidade-digital/) precisaria de um ícone ou [**link** para o Github](https://github.com/okfn-brasil/identidade-digital).

**Comment by yaso** [comment]
@ppKrauss vou te dar acesso de escrita, pull request sao sempre bem vindos :-D

**Comment by ppKrauss** [comment]
Oi @yaso, já que é bem vindo, mandei um *pull request* ;-)
