### ISSUE TITLE
quebrando Transparência em Transparência e Acesso

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/identidade-digital#14]
Conforme [post no DiscussOKBr](https://discuss.okfn.org/t/manifesto-sobre-identificacao-digital-no-brasil/4203/2), ainda sujeito a discussões, 

*  questão da *"Transparência vs Acesso"*... Nos termos da nossa CF de 1988, o art. 5º, inciso XIV, ela assegura “a todos o **acesso** à informação”; o art. 216, § 2º estabelece obrigatoriedade da franquia ao acesso. Nos termos da [LAI](http://www.lexml.gov.br/urn/urn:lex:br:federal:lei:2011-11-18;12527) idem, faz uso do termo "acesso" na mesma acepção. A *"transparência"* é em geral tratada como tópico distinto. Talvez coubesse o mesmo tipo de separação no manifesto... 

Enfim: a sugestão distinguir melhor a semântica de [transparência](https://www.wikidata.org/wiki/Q535347), criando o tópico "Acesso" a partir do desmembramento do tópico "Transparência".

-----

Como poderia ficar o novo texto:

  * ### TRANSPARÊNCIA
Os atos, normas técnicas e demais decisões relativas ao sistema de identificação, ao seu custo de aquisição, e a sua operação devem ser publicados em Diário Oficial, e seus dados expressos em formatos abertos.

  * ### ACESSO À INFORMAÇÃO
O cidadão deve ter acesso a todos os seus dados pessoais constantes no sistema de identificação, assim como saber quem teve acesso a estes e para qual finalidade, de maneira facilitada, clara e sem custos.

**Comment by uira** [comment]
@ppKrauss, fazendo um comentário aqui muito mais sobre a forma do que sobre o conteúdo:

você sabe como funcionam os Pull Requests?

Eu acho que essa discussão ficaria muito mais clara num PR. 

Se quiser posso te explicar como fazer.

**Comment by ppKrauss** [comment]
Oi @uira, obrigado pelo apoio (!), agora que temos o `index.md` ficou mais fácil para qualquer um editar direto... Você e o @decko fizeram um bom trabalho, depois podemos completar incluindo o CSS da @yaso que dava um acabamento bacana.

Sim, conheço os Pull Requests, mas fiquei sem graça de ir pondo a mão no texto (feito Wiki) sem antes debater a alteração: acho que uma boa prática é aguardar "votos" (*likes* ou discussão convergente) antes de alterar... Outra boa prática é aproveitar os redatores do projeto, acolhendo e concretizando com mais rapidez as sugestões por vezes vagas aqui das *issues*.

-----

## Dinâmica do projeto

Pelo que reparei já temos 2 ou mais redatores nesse projeto, então basta o redator citar no _commit_ o número da _issue_ associada ("#"+número)... Conferindo:

1. Você está concordando com a modificação do `index.md` aqui sugerida?

2. Acha melhor esperamos por mais "likes" ou manifestações favoráveis a esta *issue*?

3. Assumiria como redator desse fragmento de texto? <br/>O importante é citar a _issue_ no campo do *commit*, algo como <br/> &nbsp; "quebrando item Transparência conforme issue #14".

**Comment by thiagorondon** [comment]
@ppKrauss Concordo com tua abordagem, faz sentido o desmembramento. Até o momento ninguém se pronunciou contrário. Você pode criar um pull request para esta contribuição ?
