### ISSUE TITLE
Licensa incorreta

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/identidade-digital#18]
O texto [index.md](https://github.com/okfn-brasil/identidade-digital/blob/master/index.md), foco do projeto, não é um software, basta um CC-BY ou CC-BY-SA... Está errado usar [GPL no arquivo LICENSE](https://github.com/okfn-brasil/identidade-digital/blob/master/LICENSE). Nem precisa de arquivo, é lícito citar com abreviação padrão e link oficial para a licença, no final do texto (index.md).

**Comment by uira** [comment]
Mas a vantagem do arquivo [LICENSE](https://github.com/okfn-brasil/identidade-digital/blob/master/LICENSE) é justamente pq aplica a licença a todo o conteúdo do repositório, e não somente ao index.

**Comment by yaso** [comment]
@ppKrauss Está errado usar a GPL, mas também estaria errado citar um CC-BY visto que entendi que pode ser visto como documentacão e não como obra intelectual com copyright da OKbr (é uma construcao coletiva) Entao, sugiro que a gente mude pra https://www.gnu.org/licenses/fdl-1.3.en.html

**Comment by ppKrauss** [comment]
Oi @uira e @yaso, pois é... To reparando que não parece ser algo tão simples como uma correção ortográfica...  Acho que é o caso de [jogar para a discussão mais ampla](https://discuss.okfn.org/t/manifesto-sobre-identificacao-digital-no-brasil/4203/16): *"qual a licença a OKBR vai adotar nos seus manifestos e cia?"*

Em alguns casos fica até melhor usar o [CC0](https://creativecommons.org/publicdomain/zero/1.0/) para dedicar ao domínio público...  Cabe também lembrar que a [OpenDefinition](http://opendefinition.org/od/2.1/en/) (que usa github pro projeto e pro texto igualzinho nóis) adotou explicitamente [CC-BY-4](https://creativecommons.org/licenses/by/4.0/) no "texto do manifesto", e implicitamente [a mesma licença pro restante do projeto](https://github.com/okfn/opendefinition/blob/gh-pages/LICENSE).

PS: para quem não conhece, a grande diferença da CC-BY-4 para a CC-BY-3, é que agora ela pode incorporar documentação, é de certa forma tão ampla quanto a [Affero GPL](https://en.wikipedia.org/wiki/Affero_General_Public_License).

**Comment by ppKrauss** [comment]
Ninguém mais discutiu e incluímos no texto a CC-BY-3, já tá no commit. Querendo mudar, só reabrir essa issue.
