### ISSUE TITLE
Texto da proposta em Markdown

### ISSUE THREAD

**Issue by decko** [okfn-brasil/identidade-digital#2]
A proposta está contida num arquivo HTML. Isso dificulta as contribuições via github já que este não possui um visualizador para esse tipo de arquivo.

Manter a proposta em Markdown e transformar para HTML é fácil e deve permitir melhores contribuições para o texto.

**Comment by thiagorondon** [comment]
ótima proposta, acabei de criar um branch novo só com o markdown. Aproveite a versão criada anteriormente, e atualizei o conteúdo:

https://github.com/okfn-brasil/identidade-digital/blob/markdown/index.md
