### ISSUE TITLE
Sugestões para a introdução do manifesto

### ISSUE THREAD

**Issue by ppKrauss** [okfn-brasil/identidade-digital#21]
Transcrevendo as "Sugestões para a introdução do manifesto" do @claudiommachado,

Ver https://github.com/okfn-brasil/identidade-digital/pull/20/commits/787d808c36b6fbf46f904cb803d40a4bfe5bbb48

-----

Estamos nessa *issue* olhando para a [v0.1 do Manifesto](https://github.com/okfn-brasil/identidade-digital/releases/tag/0.1)...

## Alterações propostas pelo Cláudio à v0.1

(depois do parágrafo inicial...)

> A idéia de criação de um “Cadastro Nacional de Acesso à Internet” prevendo a criação de um mecanismo de identificação dos usuários e a introdução de mecanismos de controle de acesso a serviços e conteúdos têm sido recorrente no Brasil.

**(adiciona)** As discussões em torno deles vem mostrando a inviabilidade técnica da implementação de cadastros com essas finalidades, mas lamentavelmente não vem sendo discutidas alternativas adequadas para a devida identificação digital no Brasil.

(e troca...)

> Tratar de identificação digital também é falar de cidadania, segurança e privacidade do cidadão. Sistemas de identificação digital devem garantir que os cidadãos tenham controle e confiança sobre como as suas informações serão utilizadas em um sistema de identificação, que deve ser construído privilegiando a transparência e controle do cidadão sobre seus dados e reprimindo qualquer utilização abusiva ou vazamento indevido destes.

**(troca por)** 
Este manifesto propõe um conjunto de princípios para a construção de serviços de identificação de pessoas na Internet. É um convite para que cidadãos, organizações da sociedade civil, empresas, além do poder público discutam o tema.

**(e acrescenta)**

Esperamos, com isso, contribuir com a construção de uma política de identificação digital no Brasil, que respeite o Marco Civil da Internet e as caractersticas técnicas do funcionamento da rede mundial de computadores.

O Congresso Nacional vem realizando um debate relevante sobre a reformulação do modelo de organização da identificação civil no Brasil,  em torno da criação da base biométrica nacional pelo Tribunal Superior Eleitoral e a sua institucionalização com o Projeto de Lei 1.775/2015, cujo substitutivo em discussão institui a ICN – a Identidade Civil Nacional. 

A implementação do projeto ICN, independentemente de eventuais questionamentos ao seu modelo tecnológico, permitirá um aprimoramento significativo na organização dos serviços de identificação civil mantidos pelos governos estaduais, com impacto positivo em diversos setores da sociedade brasileira.
 
Entendemos que é fundamental aproveitar esse momento para ampliar esse debate com a inclusão de uma política de identificação digital para o Brasil aderente à arquitetura técnica que viabiliza o funcionamento da Internet. Uma política que impulsione o uso seguro de serviços eletrônicos, sejam eles públicos ou privados, assim como, também, trate adequadamente os desafios à proteção da privacidade e dos dados pessoais que são amplificados na Internet.

**(daí em diante continua igual...)**

> Os princípios que devem ser considerados na implementação da identificação digital no Brasil são:

**Comment by ppKrauss** [comment]
Parecer pessoal:  

* julgo importante citar o [Projeto de Lei 1.775/2015 da Câmara dos Deputados](http://www.lexml.gov.br/urn/urn:lex:br:camara.deputados:projeto.lei;pl:2015-06-01;1775)
 (mas sugiro que seja com esse **link** para o LexML), mas não acompanhei a redação inicial, não sei porque não foi citado antes...Vou apenas supor que, como eu, todos achariam bom. 

* sugiro fortemente resumir os demais acréscimos, **o texto "precisa" ser enxuto**, tomo como referência a [OpenDefinition](http://opendefinition.org/od/2.0/pt-br/) e outros manifestos de sucesso.

Conclusão: já que temos a [tag 0.1](https://github.com/okfn-brasil/identidade-digital/releases/tag/0.1) podemos **ir tocando como Wiki**, ou seja, o Cláudio fez a parte dele, depois vem alguém e melhora.

**Comment by thiagorondon** [comment]
@ppKrauss não prefere enviar um pull request suas sugestões ?

**Comment by yaso** [comment]
Jaja escrevo por lá, mas sinto que aqui
"permitirá um aprimoramento significativo na organização dos serviços de
identificação civil mantidos pelos governos estaduais, com impacto positivo
em diversos setores da sociedade brasileira.
"


Estamos fazendo propaganda do governo. Preecisa mudar.

yaso

**Comment by claudiommachado** [comment]
O que está em questão não fazer propaganda do governo, a discussão não é essa mesmo, mas qual o entendimento que temos em relação ao projeto ICN.

Essa frase reflete meu ponto de vista, que sendo transparente, é favorável ao ICN.

Abs! Claudio.

**Comment by yaso** [comment]
Pois eh. Minha visao pessoal é de que o ICN é um projeto mal-feito,
completamente perdido no tempo e deslocado da realidade.
Mas e ai, nao podemos colocar nossao visao pessoal no doc.

Podemos?

O.o


∞ yaso.is
∞ Fellow of the Berkman Klein Center at Harvard

2017-01-12 15:10 GMT-05:00 claudiommachado <notifications@github.com>:

> O que está em questão não fazer propaganda do governo, a discussão não é
> essa mesmo, mas qual o entendimento que temos em relação ao projeto ICN.
>
> Essa frase reflete meu ponto de vista, que sendo transparente, é favorável
> ao ICN.
>
> Abs! Claudio.
>

**Comment by claudiommachado** [comment]
Proponha uma redação. Se o grupo achar necessário, como o Thiago sinalizou, fazemos uma nova discussão.

Acho que possível construir uma visão comum do grupo que contemple diferentes pontos de vista. Destaco que não é um manifesto sobre o ICN, mas sobre identificacao digital.

Abs! Claudio.

**Comment by yaso** [comment]
Mais uma vez,

se nao eh um manifesto sobre o ICN nao vejo porque colocar o ICN na intro
nao acho nem que é consenso de que o estado precisa identificar pra
oferecer assistencia e servicos melhores
e entendo que estariamos assumindo uma visao unilateral sobre o assunto em
uma carta de principios, o que nao seria legal pra OKbr em termos de
organizacao

ja propus a redacao
era o comit anterior

Se o caso é apoiar o ICN, sugiro outra reuniao, num role separado.




∞ yaso.is
∞ Fellow of the Berkman Klein Center at Harvard

**Comment by claudiommachado** [comment]
Concordo com uma redação sem juízo de valor ou posicionamento em relação ao ICN, agora ignorar o projeto seria, na minha opinião, se descolar da realidade.

Acho que esse é um ponto central e justifica uma nova discussão. Mas seria bom que fosse objetiva, tipo as posições seria compartilhadas previamente, uma rodada de esclarecimentos e uma nova tentativa de formar um consenso.

Abs! Claudio.

**Comment by yaso** [comment]
Claudio!

Boa, concordo em nao falar no projeto no manifesto. Fazemos o manifesto e
depois acho LYNDO a ok se envolver com o projeto. mas o manifesto nao eh
lugar pra manifestar posicao sobre a proposta. O que vc acha?



∞ yaso.is
∞ Fellow of the Berkman Klein Center at Harvard

**Comment by claudiommachado** [comment]
Concordo em explicitarmos que o manifesto não significa um posicionamento sobre o ICN ou qualquer outro projeto, mas um manifesto de princípios para a construção de uma política de identidade digital.

Abs! Claudio.
