### ISSUE TITLE
UNICIDADE (para discussão)

### ISSUE THREAD

**Issue by thiagorondon** [okfn-brasil/identidade-digital#5]
Deve-se evitar duplicidade no armazenamento de dados de cidadãos pelo setor público, através de medidas como a utilizacão de padrões e a definição de responsabilidades sobre categorias de dados, evitando desperdício, redundâncias e principalmente permitindo o controle efetivo pelo cidadão sobre seus dados.

**Comment by thiagorondon** [comment]
Reforçando comentário do Doneda - pode ser redundante pq o famigerado Decreto 8789 sobre compartilhamento de dados já aponta para uma interligação de bancos de dados (o que vai contra algumas características garantidas pela decentralização) e não sei se é o caso de reforçar aqui.

**Comment by solstag** [comment]
Eu diria que deveríamos reforçar o contrário: há bancos de dados que propositalmente devem ser mantidos independentes e não devem em hipótese alguma serem integrados para não facilitar abusos, cruzar incentivos à manipulação, e até - dependendo de como a coisa for feita - dificultar fraudes por permitir comparações entre bancos administrados independentemente.

O banco de dados utilisado para identificação eleitoral, por exemplo e criticamente, deve ter única e exclusivamente esse fim.

**Comment by ppKrauss** [comment]
Oi @thiagorondon, eu não conhecia esse Decreto, convém até abrir um pouco a discussão sobre ele, parece ser (para o bem ou para o mal) uma peça importante: [Decreto Federal nº 8.789 de 2016](http://www.lexml.gov.br/urn/urn:lex:br:federal:decreto:2016-06-29;8789), *"Dispõe sobre o compartilhamento de bases de dados na administração pública federal"*.

@solstag, sou mais na linha do Thiago, dados não devem jamais ser duplicados em sistemas de gestão de dados... E se existem dois ou mais sistemas, há que se entender e justificar muito bem a duplicação... Claro, entendo seu trauma, e de qualquer brasileiro, mas a culpa não é da [normalização dos dados](https://en.wikipedia.org/wiki/Database_normalization)... O problema tem origem na falta de curadoria de dados, falta de democracia nas curadorias, e alto índice de "donos de dados" no governo e até mesmo nas ONGs e universidades.

**Sugestão**: que  tal discutirmos o modelo "centralizado" do [LexML](http://projeto.lexml.gov.br/)? que é compatível com modelos até antigos de "backup descentralizado", como o [LOCKSS](https://en.wikipedia.org/wiki/LOCKSS).  Acho que focando em casos os consensos e dissensos ficam mais simples de se evidenciar.

**Comment by yaso** [comment]
Lembrando que "evitar duplicidade" não existe em ambiente digital. Restringir acesso é uma coisa importante porque quando você tem dados você necessariamente vai ter cópias. Eu diria evitar acesso indevido, mas evitar duplicidades não. Inclusive, a duplicidade pode ajudar na desambiguacao em cenário de multiplicidade de fontes.

**Comment by ppKrauss** [comment]
Oi @yaso, o que você e o @solstag  estão colocando é a questão do "direito de preservar, redistribuir, etc." já que é coisa pública... E das vantagens de um sistema distribuído, etc.

Enquanto eu e o @thiagorondon  estamos falando de [normalização de dados](https://en.wikipedia.org/wiki/Database_normalization) e do quanto o nosso governo é ruim ao não oferecer dados normalizados... E aí, cada um falando numa língua??  Acredito que não, faltou talvez enfatizar o personagem central que é a **autoridade do dado**.

-----

Maiores detalhes ver [Unicidade do original e autoridade do dado](https://github.com/okfn-brasil/identidade-digital/wiki/Gloss%C3%A1rio:-unicidade-do-original-e-autoridade-do-dado) na Wiki deste git.

**Comment by solstag** [comment]
Oi Peter,

Não, nada a ver. Ao meu ver você entendeu errado do que estamos falando. Nada do que você comenta tem qualquer efeito sobre o que eu ou a Yaso apontamos e criticamos. Ao meu ver continua sendo importante remover esse ponto sobre unicidade e ressaltar a importância da não integração de determinados bancos de dados que não devem estar sujeitos aos mesmos interesses que outros.

Ademais, eu entendo perfeitamente o que você diz sobre autoridade, e não tenho dúvida que a Yaso também. Pense mais em quem são seus interlocutores e lembre-se que estamos em 2017, se alguém quer entender um conceito faz uma busca e pronto. Não há razão para, sem solicitação, introduzir um monólogo com mais parágrafos do que toda a discussão precedente.

Abs! E feliz ano novo =D

**Comment by ppKrauss** [comment]
Fala Abdo, feliz ano novo!

Então  @solstag, tanto concordo que me antecipei e separei com um bigode  a parte "didática", não precisa dar bronca, já estava explicitando que estou ciente...  ;-)
Para não poluir misturando "glossário" com conteúdo principal, transferi para a Wiki, que é de fato o local mais correto, basta citar o link (tá [aqui](https://github.com/okfn-brasil/identidade-digital/wiki/Gloss%C3%A1rio:-unicidade-do-original-e-autoridade-do-dado)). Também incluí essa  recomendação, [convencionando o uso de tópicos Wiki com prefixo "Glossário:"](https://github.com/okfn-brasil/identidade-digital/wiki/Recomenda%C3%A7%C3%B5es-para-o-uso-dos-espa%C3%A7os-de-discuss%C3%A3o#recomenda%C3%A7%C3%B5es).

Ademais eu e você podemos endossar o que foi dito por outros, mas não falar por eles: aguardemos um "Hello!" da @yaso e do @thiagorondon ;-)

-----

(olha o bigode estruturando meu *post* em mais de uma parte)

Pelo que interpreto do seu comentário você está dizendo que essa *issue* não é uma discussão bate-papo, mas é [uma *issue de bug*](https://github.com/okfn-brasil/identidade-digital/issues?utf8=%E2%9C%93&q=is%3Aissue%20%20label%3Abug%20)... Acho que deveria abrir outra issue só para reclamar do que julga ser um bug. Eu pessoalmente nem sequer fui capaz de achar a palavra "unicidade" ou "único" [no texto](https://github.com/okfn-brasil/identidade-digital/blob/master/index.md).

-----

Quanto ao seu comentário 

> ...quem são seus interlocutores...

Difícil, a OKBr passou por uma crise, perdeu muita gente, e agora está chegando gente nova: como aqui a comunicação é aberta e pública, é a elas que também me dirijo e busco acolher.

A OKBr tem esse perfil, que não é um problema, é da natureza de um coletivo mais **plural** e menos intimamente alinhado: aqui as pessoas defendem ideias e ideais, com unhas e dentes, é comum (e você é exemplo vivo disso!) as visões de mundo levarem a interpretações antagônicas do mesmo texto.
