### ISSUE TITLE
HTML ou Markdown?

### ISSUE THREAD

**Issue by solstag** [okfn-brasil/identidade-digital#6]
E aí, com qual seguimos? Era bom ficar um só documento, senão alguém vai ter q ficar passando mudanças pra lá e pra cá, ou todo mundo vai ter que ficar mudando ambos...

**Comment by uira** [comment]
Voto no **MarkDown**!

E acho que essa decisão é importante para não desanimar os animados ;)

**Comment by uira** [comment]
Acabo de fazer um PR incorporando várias modificações feitas pelo Tiago e removendo a versão em .html

https://github.com/okfn-brasil/identidade-digital/pull/10
